<!DOCTYPE html>
<html lang="en">

<?php require_once "app/views/template/head.php"; ?>

<body style="background-image:url('<?= ASSETS ?>/Isi tutorial.png')" class="bg-cover">
    <div class="w-full px-20 pt-10 pb-20 relative">
        <a class="absolute" href="<?= BASE_URL ?>/dashboard">
            <img class="h-10 w-10" src="<?= ASSETS ?>/Double left.png">
        </a>
        <h2 class="header2 text-center mb-10"><?= ucwords($data["db"]["tutorial"]["nama"]) ?></h2>
        <p class="body-text indent-8">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo facilis molestias consequatur impedit nihil eveniet ad commodi ex sint sunt eos, aperiam quam dolorem similique eaque quos numquam, debitis perferendis? Repellat, eaque optio magni quidem commodi tenetur, labore fuga eos suscipit est libero ad porro fugit maxime? Veritatis vel amet quis perferendis molestias quibusdam blanditiis fuga, maxime dolorem nostrum tempora provident in doloremque, at nesciunt animi quidem reiciendis tempore repellendus neque? Mollitia doloremque cupiditate aut. Dolores unde quo, laudantium atque quaerat repudiandae iusto dolorem impedit quibusdam vitae voluptates nulla esse harum. Cum molestias rerum, dolorem cupiditate voluptates officiis at eaque obcaecati provident autem distinctio architecto quam dicta earum officia aliquid alias ea corporis perspiciatis nobis quibusdam, quidem maxime. Harum rerum quaerat quam nobis totam saepe delectus, eos dolore officia nemo odio? Qui et quam velit saepe totam praesentium doloribus facilis id magni facere eaque eos esse dolorem dicta nulla fugiat, rem mollitia cupiditate temporibus laboriosam, hic odio. Aliquam aliquid, aspernatur rem nulla earum itaque libero obcaecati dicta eum ducimus architecto non a saepe ipsam commodi neque nihil nisi voluptatem. Iusto beatae iste, facilis corrupti exercitationem velit perferendis minus illum veniam aperiam hic culpa eveniet autem, reiciendis distinctio fuga. Ut, architecto!</p>
        <br>
        <p class="body-text indent-8">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo nostrum fugiat sed dolore illum earum velit, voluptate debitis sapiente maiores ut corporis, in rerum officia quod odit deserunt deleniti iure quis dolorum commodi animi! Nemo ex, veritatis minus hic, necessitatibus dolorum inventore ipsa quod odit sapiente nobis labore reiciendis vitae nihil magni ullam, dolor saepe? Atque culpa rem necessitatibus praesentium consequuntur in. Fugiat pariatur, sapiente ea harum maxime nostrum quam quod exercitationem provident dolorem reprehenderit culpa! Corporis reprehenderit minima illum debitis, est, quis accusamus nemo iure dignissimos nihil repellendus minus beatae esse nobis quod rerum quo vero dicta temporibus perferendis ut quasi doloremque reiciendis expedita? Totam expedita, officiis suscipit delectus nesciunt quasi! Obcaecati at impedit alias doloremque, iusto consectetur iste assumenda modi enim, laborum tenetur. Perferendis, maiores quia? Sunt ipsa exercitationem rerum temporibus mollitia fugit nulla a tenetur soluta odio.</p>
        <br>
        <p class="body-text indent-8">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi adipisci delectus incidunt ut facilis deleniti sint, culpa quae non aliquam ipsam asperiores impedit quidem deserunt voluptatem? Ipsum dolorem adipisci minima debitis possimus distinctio nesciunt repellendus temporibus quod, ex assumenda accusamus. Dolorem officia delectus, ex excepturi esse voluptate illum inventore magnam officiis iure expedita consequatur ad vel voluptatibus accusantium possimus, maxime fugiat atque distinctio. Cumque quaerat magnam blanditiis aliquid pariatur! Aut repellendus earum perferendis sed iusto eius molestias. Doloremque fuga, eum nemo corrupti sequi officia nulla, harum animi dolore aliquid distinctio quod in minus vitae adipisci temporibus iure enim aperiam ullam provident asperiores optio! Dicta officia soluta, voluptas exercitationem deserunt fugiat? Sapiente quisquam animi esse, rerum vitae, explicabo possimus, inventore exercitationem laboriosam aliquid voluptatum!</p>
        <br>
        <p class="body-text indent-8">Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias consectetur animi labore? Possimus nobis eum veniam nostrum tempora deleniti repudiandae vel molestias id, doloremque natus. Iure laborum debitis consectetur fuga, sint obcaecati ipsa sit aspernatur eaque delectus beatae quam laudantium enim earum natus, possimus sed harum architecto placeat voluptatibus cum. Iste rerum, natus mollitia repellat beatae corrupti eos sequi eius tenetur! Voluptates eligendi, cumque tenetur facilis provident quod esse illo in nesciunt similique nulla repudiandae, veniam sit totam dignissimos ex laboriosam. Voluptatibus laboriosam sed mollitia in natus. Blanditiis, voluptatem. Doloremque ipsa quis natus veritatis et quia maiores quo eveniet, tempore velit asperiores cumque magnam ipsum soluta cum dolorum distinctio quasi non quod aut possimus minima, aliquid delectus. Quidem non hic voluptates deserunt voluptatibus architecto fugit, eum explicabo reiciendis ipsum accusantium mollitia nam, consectetur laudantium sapiente quas, tenetur vel! Quas, veniam dolore, unde cum accusantium nulla doloribus voluptates iure cupiditate sapiente placeat excepturi dolores delectus quae earum ipsum eligendi neque expedita est quam! Repellat, laborum? Voluptate repellat quisquam dignissimos corrupti dolorem facere voluptatum quos omnis facilis rem, vitae odio tempora delectus? Itaque ipsum officiis non deserunt perferendis, soluta officia sint at dicta atque tenetur provident ducimus velit recusandae qui explicabo quis. Quidem recusandae at cum obcaecati officiis fugit voluptas vero explicabo laborum minus quod quia, pariatur doloribus deleniti, nemo rerum voluptatum?</p>
        <br>
        <a class="bg-primer1 rounded-md py-2 px-8 text-white body-text mx-auto" href="<?= BASE_URL ?>/tutorial/complete/<?= $data["db"]["tutorial"]["id_tutorial"] ?>">
            Selesai
        </a>
    </div>
</body>

</html>