# file: .github/workflows/preview.yaml
on:
  push:
    branches:
      - docker-compose

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Set outputs
      id: vars
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT
    - name: Check outputs
      run: echo ${SHORT_SHA}
    - name: Context
      uses: okteto/context@latest
      with:
        url: ${{secrets.OKTETO_URL}}
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: Deploy preview environment
      uses: okteto/deploy-preview@latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.vars.outputs.SHORT_SHA }}-usernob
        timeout: 15m
